#!/bin/sh
#
# everarch - the hopefully ever lasting archive
# Copyright (C) 2021-2023  Markus Peröbner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
set -e

attr_trans_ref=`evr put < "/opt/evr/attr-spec/attr-trans.xslt"`

evr -f 3 sign-put <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<claim-set
    xmlns="https://evr.ma300k.de/claims/"
    xmlns:dc="http://purl.org/dc/terms/"
    dc:created="2023-12-18T20:00:00.000000Z"
    >
  <attr-spec>
    <attr-def k="class" type="str">
        <example>file</example>
        <example>unknown</example>
    </attr-def>
    <attr-def k="file" type="str"/>
    <attr-def k="file-size" type="int" example="4238473"/>
    <attr-def k="title" type="str" example="some title"/>
    <attr-def k="unknown-claim-name" type="str" example="some-tag"/>
    <attr-def k="unknown-claim-ns" type="str" example="https://acme.org/xml-ns"/>

    <transformation type="xslt" blob="${attr_trans_ref}"/>
  </attr-spec>
</claim-set>
EOF
