#!/bin/bash
set -e
set -o pipefail
. ../config

stop(){
    if [[ -n "${ipid}" ]]
    then
        kill -s sigint "${ipid}"
        wait "${ipid}" || true
    fi
    kill -s sigint "${spid}"
    wait "${spid}" || true
    if [[ -e 'storage/lock' ]]
    then
        echo "storage/lock still existing after storage quit" >&2
        exit 1
    fi
    rm -rf 'storage' 'attr-index'
}

rm -rf 'storage' 'attr-index'
mkdir 'storage' 'attr-index'

evr-glacier-storage &
spid=$!
trap stop EXIT

wait_for_glacier_storage

echo "Uploading basic attr-spec…"
basic_xslt_ref=`evr put < basic.xslt`
evr -f 3 sign-put <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<claim-set
    xmlns="https://evr.ma300k.de/claims/"
    xmlns:dc="http://purl.org/dc/terms/"
    dc:created="2022-03-01T00:00:00.000000Z"
    >
  <attr-spec>
    <attr-def k="tag" type="str"/>
    <attr-def k="title" type="str"/>
    <transformation type="xslt" blob="${basic_xslt_ref}"/>
  </attr-spec>
</claim-set>
EOF

echo "Uploading test claim…"
test_ref=`evr -f 1 sign-put < attr-claim.xml`

echo "Starting evr-attr-index…"
evr-attr-index &
ipid=$!

sleep 1

echo "Running test queries…"

results=`nc localhost 2362 <<EOF
s tag=no-such-tag-exists
exit
EOF`
if [[ "${results}" != "OK" ]]
then
    echo "Unexpected result from tag=no-such-tag-exists query: ${results}" >&2
    exit 1
fi

results=`nc localhost 2362 <<EOF
s tag=todo
exit
EOF`
if [[ "${results}" != "OK
${test_ref}-0000" ]]
then
    echo "Unexpected result from tag=todo query: ${results}" >&2
    exit 1
fi

results=`nc localhost 2362 <<EOF
s select * where tag=todo
exit
EOF`
if [[ "${results}" != "OK
${test_ref}-0000
	tag=todo
	title=test claim" ]]
then
    echo "Unexpected result from select * where tag=todo query: ${results}" >&2
    exit 1
fi

results=`nc localhost 2362 <<EOF
s select * where ref=${test_ref}-0000
exit
EOF`
if [[ "${results}" != "OK
${test_ref}-0000
	tag=todo
	title=test claim" ]]
then
    echo "Unexpected result from 'select * where s ref=${test_ref}-0000' query: ${results}" >&2
    exit 1
fi

results=`nc localhost 2362 <<EOF
s waduup?
exit
EOF`
if [[ "${results}" != "ERROR syntax error, unexpected UNKNOWN, expecting EQ" ]]
then
    echo "Unexpected result from 's waruup?' query: ${results}" >&2
    exit 1
fi

results=`nc localhost 2362 <<EOF
c ${test_ref}-0000
exit
EOF`
if [[ "${results}" != "${test_ref}-0000" ]]
then
    echo "Unexpected result from 'c ${test_ref}-0000' query: ${results}" >&2
    exit 1
fi

echo "Stopping…"
