# everarch - the hopefully ever lasting archive
# Copyright (C) 2021-2023  Markus Peröbner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FROM docker.io/library/alpine:3.18 AS image
LABEL org.opencontainers.image.authors="markus.peroebner@gmail.com"
LABEL org.opencontainers.image.licenses="AGPL-3.0"
LABEL org.opencontainers.image.source="https://github.com/marook/everarch"

# the volume /pub exposes the public GPG keys used and auth-token
# necessary to access the other evr services.
VOLUME /pub

COPY README AUTHORS COPYING /opt/evr/
COPY etc/podman/evr-join-link/entrypoint.sh /
COPY etc/podman/entrypoints/wait_for_file /opt/evr/entrypoint/

CMD ["/entrypoint.sh"]
