#!/bin/bash
set -e
. ../config

allocate_ports
write_evr_conf
trap stop_everarch_servers EXIT

start_glacier_storage
wait_for_glacier_storage

# launch two watchers so there is more pressure on the thread
# synchronization within evr-glacier-storage
( evr watch > /dev/null ) &
wpid1=$!
( evr watch > /dev/null ) &
wpid2=$!

glacier-benchmark > glacier-benchmark.log

kill "${wpid1}"
kill "${wpid2}"

storage_size=`du -hs storage | awk '{print $1}'`
echo "Produced ${storage_size} storage"
