#!/bin/bash
set -e
. ../config

stop(){
    kill -s sigint "${spid}"
    wait "${spid}" || true
    if [[ -e 'storage/lock' ]]
    then
        echo "storage/lock still existing after storage quit" >&2
        exit 1
    fi
    rm -rf 'storage' 'running'
}

rm -rf 'storage'
mkdir 'storage'

evr-glacier-storage >/dev/null &
spid=$!
trap stop EXIT

wait_for_glacier_storage

put_pids=
touch running
put_loops=`grep '^cpu\\scores' '/proc/cpuinfo' | uniq |  awk '{print $4}'`
put_loops=`expr 20 + ${put_loops}`
echo "Starting ${put_loops} put loops…"
i=0
while [[ $i -lt $put_loops ]]
do
    ./put-loop &
    p=$!
    put_pids="${put_pids} ${p}"
    i=`expr -- "${i}" '+' '1'`
done

echo "Running…"
sleep 10

echo "Stopping…"
rm running

for pid in $put_pids
do
    kill "${pid}" && wait "${pid}" || true
done

storage_size=`du -hs storage | awk '{print $1}'`
echo "Produced ${storage_size} storage"
