#!/bin/bash
set -e
. ../config

allocate_ports
write_evr_conf
trap stop_everarch_servers EXIT

rm -rf -- "${glacier_storage_bucket_dir}"
mkdir -- "${glacier_storage_bucket_dir}"
echo "Starting evr-glacier-storage…"
evr-glacier-storage --port "${glacier_storage_port}" --cert "${glacier_storage_cert_path}" --key "${script_dir}/../tls/glacier-key.pem" --auth-token "${glacier_storage_auth_token}" --bucket-dir-path "${glacier_storage_bucket_dir}" > /dev/null &
glacier_storage_pid=$!

wait_for_glacier_storage

# launch two watchers so there is more pressure on the thread
# synchronization within evr-glacier-storage
( evr watch > /dev/null ) &
wpid1=$!
( evr watch > /dev/null ) &
wpid2=$!

put_pids=
touch running
put_loops=`grep '^cpu\\scores' '/proc/cpuinfo' | uniq |  awk '{print $4}'`
put_loops=`expr 20 + ${put_loops}`
echo "Starting ${put_loops} put loops…"
i=0
while [[ $i -lt $put_loops ]]
do
    ./put-loop &
    p=$!
    put_pids="${put_pids} ${p}"
    i=`expr -- "${i}" '+' '1'`
done

echo "Running…"
sleep 10

echo "Stopping…"
rm running

kill "${wpid1}"
kill "${wpid2}"

for pid in $put_pids
do
    wait "${pid}" || true
done

storage_size=`du -hs storage | awk '{print $1}'`
echo "Produced ${storage_size} storage"
