#!/bin/bash
set -e
set -o pipefail
. ../config

if [[ "${HAS_FUSE}" != 'true' ]]
then
    echo "Skipping fs integration test because fuse is not available."
    exit 0
fi

allocate_ports
write_evr_conf
trap stop_everarch_servers EXIT

start_glacier_storage
wait_for_glacier_storage

echo "Uploading basic attr-spec…"
basic_xslt_ref=`evr put < basic.xslt`
evr -f 3 sign-put <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<claim-set
    xmlns="https://evr.ma300k.de/claims/"
    xmlns:dc="http://purl.org/dc/terms/"
    dc:created="2022-03-01T00:00:00.000000Z"
    >
  <attr-spec>
    <attr-def k="tag" type="str"/>
    <attr-def k="title" type="str"/>
    <attr-def k="category" type="claim-ref"/>
    <transformation type="xslt" blob="${basic_xslt_ref}"/>
  </attr-spec>
</claim-set>
EOF

fs_xslt_ref=`evr put < fs.xslt`
msg_file_ref=`echo 'hello world!' | evr post-file --title 'msg.txt'`
dd bs=4000 count=300 if=/dev/urandom | evr post-file --title 'little-random.bin'
now=`evr_now`
category_ref=`evr sign-put -f 1 <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<claim-set
    xmlns="https://evr.ma300k.de/claims/"
    xmlns:dc="http://purl.org/dc/terms/"
    dc:created="${now}"
    >
  <attr>
    <a op="=" k="title" v="my-category"/>
  </attr>
</claim-set>
EOF`
evr sign-put -f 1 <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<claim-set
    xmlns="https://evr.ma300k.de/claims/"
    xmlns:dc="http://purl.org/dc/terms/"
    dc:created="${now}"
    >
  <attr seed="${msg_file_ref}">
    <a op="=" k="category" v="${category_ref}-0000"/>
  </attr>
</claim-set>
EOF

start_attr_index
wait_for_attr_index

evr_fs_opts='-T category'
mount_evr_fs "${fs_xslt_ref}"

find_mnt=`find mnt`
if [[ "${find_mnt}" != 'mnt
mnt/.evr
mnt/.evr/online
mnt/test-subdir
mnt/test-subdir/little-random.bin
mnt/test-subdir/cat-my-category
mnt/test-subdir/cat-my-category/msg.txt' ]]
then
    echo "Unexpected find mnt: ${find_mnt}" >&2
    exit 1
fi

online=`cat mnt/.evr/online`
if [[ "${online}" != '1' ]]
then
    echo "Expected evr-fs to be online but was: ${online}" >&2
    exit 1
fi

size_msg_txt=`stat -c '%s' mnt/test-subdir/cat-my-category/msg.txt`
if [[ "${size_msg_txt}" != '13' ]]
then
    echo "Unexpected disk usage of msg.txt: ${size_msg_txt}" >&2
    exit 1
fi

cat_msg=`cat mnt/test-subdir/cat-my-category/msg.txt`
if [[ "${cat_msg}" != 'hello world!' ]]
then
    echo "Unexpected mnt/test-subdir/msg.txt content: ${cat_msg}" >&2
    exit 1
fi

little_random_bytes=`cat mnt/test-subdir/little-random.bin | wc --bytes`
if [[ "${little_random_bytes}" != '1200000' ]]
then
    echo "Unexpected mnt/test-subdir/little-random.bin content size: ${little_random_bytes}" >&2
    exit 1
fi

# update msg.txt -> new-msg.txt
echo 'new message!' | evr post-file --seed "${msg_file_ref}" --title 'new-msg.txt'
# sleep for one second because fuse attr and entry timeouts are set to
# one second in evr-fs.c
sleep 1
wait_for_file 'mnt/test-subdir/cat-my-category/new-msg.txt'
cat_msg=`cat mnt/test-subdir/cat-my-category/new-msg.txt`
if [[ "${cat_msg}" != 'new message!' ]]
then
    echo "Unexpected mnt/test-subdir/new-msg.txt content: ${cat_msg}" >&2
    exit 1
fi
if [[ -e 'mnt/test-subdir/cat-my-category/msg.txt' ]]
then
    echo "msg.txt should have been removed but still exists" >&2
    exit 1
fi

# change dependant seed
now=`evr_now`
evr sign-put -f 1 <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<claim-set
    xmlns="https://evr.ma300k.de/claims/"
    xmlns:dc="http://purl.org/dc/terms/"
    dc:created="${now}"
    >
  <attr seed="${category_ref}-0000">
    <a op="=" k="title" v="new-category"/>
  </attr>
</claim-set>
EOF
wait_for_file 'mnt/test-subdir/cat-new-category/new-msg.txt'
cat_msg=`cat mnt/test-subdir/cat-new-category/new-msg.txt`
if [[ "${cat_msg}" != 'new message!' ]]
then
    echo "Unexpected mnt/test-subdir/new-msg.txt content: ${cat_msg}" >&2
    exit 1
fi

echo 'live content' | evr post-file --title "new-live-file.txt"
wait_for_file 'mnt/test-subdir/new-live-file.txt'

# have two different files open at the same time
mixed=`zipper 'mnt/test-subdir/cat-new-category/new-msg.txt' 'mnt/test-subdir/new-live-file.txt'`
if [[ "${mixed}" != "nleiwv em ecsosnatgeen!t" ]]
then
    echo "Unexpected zipper new-msg.txt new-live-file.txt output: ${mixed}" >&2
    exit 1
fi

# have one file open twice at the same time
mixed=`zipper 'mnt/test-subdir/cat-new-category/new-msg.txt' 'mnt/test-subdir/cat-new-category/new-msg.txt'`
if [[ "${mixed}" != "nneeww  mmeessssaaggee!!" ]]
then
    echo "Unexpected zipper new-msg.txt new-msg.txt output: ${mixed}" >&2
    exit 1
fi

# restart evr-attr-index
stop_attr_index
wait_for_content "mnt/.evr/online" '0'
start_attr_index
wait_for_attr_index
wait_for_content "mnt/.evr/online" '1'

echo 'after evr-attr-index restart' | evr post-file --title "after-evr-attr-index-restart.txt"
wait_for_file 'mnt/test-subdir/after-evr-attr-index-restart.txt'

echo "Stopping…"
