#!/bin/sh
#
# everarch - the hopefully ever lasting archive
# Copyright (C) 2021-2023  Markus Peröbner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
set -e

token_name="$1"

if [ -z "${token_name}" ]
then
    echo "Usage: $0 TOKEN_NAME" >&2
    exit 1
fi

if [ ! -e "/pub/${token_name}-auth-token" ]
then
    echo "Generating auth-token..."
    if [ "${EVR_REUSE_GLACIER_AUTH_TOKEN}" == '1' ]
    then
        wait_for_file "/pub/evr-glacier-storage-auth-token"
        cp "/pub/evr-glacier-storage-auth-token" "/pub/${token_name}-auth-token.tmp"
    else
        openssl rand -hex 32 > "/pub/${token_name}-auth-token.tmp"
    fi
    mv "/pub/${token_name}-auth-token.tmp" "/pub/${token_name}-auth-token"
    chmod a-w "/pub/${token_name}-auth-token"
fi
