#!/usr/bin/env python3
#
# everarch - the hopefully ever lasting archive
# Copyright (C) 2021-2024  Markus Peröbner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import argparse
import json
import sys

from embeddings import add_embeddings_args, connect_chroma, build_embeddings

ollama_base_url = 'http://localhost:11434'
ollama_model = 'mistral'
chroma_db_path = './chromadb'
chroma_collection_name = 'evr'

def parse_args():
    p = argparse.ArgumentParser()
    add_embeddings_args(p)
    p.add_argument('prompt',
                   metavar='PROMPT')
    return p.parse_args()

def main(args):
    emb = build_embeddings(args, args.prompt)
    chroma = connect_chroma(args)
    results = chroma.query(
        query_embeddings=[emb],
        n_results=10,
    )
    res = []
    for i, emb_id in enumerate(results['ids'][0]):
        res.append({
            'id': emb_id,
            'doc': results['documents'][0][i],
            'dist': results['distances'][0][i],
            'meta': results['metadatas'][0][i],
        })
    json.dump(res, sys.stdout, indent='\t')

if __name__ == '__main__':
    args = parse_args()
    main(args)
