# everarch - the hopefully ever lasting archive
# Copyright (C) 2021-2023  Markus Peröbner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FROM docker.io/library/node:18.16-alpine
MAINTAINER Markus Peröbner <markus.peroebner@gmail.com>

EXPOSE 8030

# the volume /pub must provide the TLS certificate and auth-token
# necessary to access the evr-glacier-storage instance. this volume
# should be provided by the evr-glacier-storage container.
VOLUME /pub

RUN apk update && apk add libxml2 libxslt gpgme

ADD evr-websocket-server /opt/evr-websocket-server
ADD evr /bin/evr
ADD start.js /opt/evr-websocket-server/start.js

RUN cd /opt/evr-websocket-server && npm install

CMD ["/opt/evr-websocket-server/start.js"]
