# everarch - the hopefully ever lasting archive
# Copyright (C) 2021-2023  Markus Peröbner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FROM docker.io/library/alpine:3.18 AS builder
LABEL org.opencontainers.image.authors="markus.peroebner@gmail.com"
LABEL org.opencontainers.image.licenses="AGPL-3.0"
RUN apk update && apk add gcc musl-dev make autoconf automake pkgconfig libtool texinfo argp-standalone libxml2-dev libxslt-dev openssl-dev gpgme-dev libgcrypt-dev sqlite-dev
WORKDIR /root/everarch
COPY . /root/everarch
RUN autoreconf --install && ./configure && make clean && cd src && make -j 4 evr

FROM docker.io/library/node:18.16-alpine AS image
LABEL org.opencontainers.image.authors="markus.peroebner@gmail.com"
LABEL org.opencontainers.image.licenses="AGPL-3.0"

EXPOSE 8030

# the volume /pub must provide the TLS certificate and auth-token
# necessary to access the evr-glacier-storage instance. this volume
# should be provided by the evr-glacier-storage container.
VOLUME /pub

VOLUME /data

RUN apk update && apk add libxml2 libxslt gpgme

COPY README AUTHORS COPYING /opt/evr/
COPY websocket-server/lib/*.js /opt/evr/evr-websocket-server/lib/
COPY websocket-server/package.json websocket-server/package-lock.json /opt/evr/evr-websocket-server/
COPY --from=builder /root/everarch/src/evr /opt/evr/bin/
COPY etc/podman/evr-websocket-server/entrypoint.js /

ENV PATH="/opt/evr/bin:${PATH}"

RUN cd /opt/evr/evr-websocket-server && npm install

CMD ["/entrypoint.js"]
