# everarch - the hopefully ever lasting archive
# Copyright (C) 2021-2023  Markus Peröbner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FROM docker.io/library/alpine:3.18 AS image
LABEL org.opencontainers.image.authors="markus.peroebner@gmail.com"
LABEL org.opencontainers.image.licenses="AGPL-3.0"
LABEL org.opencontainers.image.source="https://github.com/marook/everarch"
RUN apk update && apk add clang musl-dev make autoconf automake pkgconfig libtool texinfo argp-standalone libxml2-dev libxslt-dev coreutils openssl openssl-dev gpgme-dev libgcrypt-dev sqlite-dev flex bison bash netcat-openbsd socat util-linux libmicrohttpd-dev curl
COPY . /root/everarch
WORKDIR /root/everarch
RUN gpg --quick-gen-key --batch --passphrase '' evr-alpine@example.org && cp testing/suite/config.alpine testing/suite/config.local && autoreconf --install && ./configure CC=clang && make clean && make -j 4 && ./test.sh
