#!/bin/bash
set -e
set -o pipefail
. ../config

stop(){
    kill -s sigint "${spid}"
    wait "${spid}" || true
    if [[ -e 'storage/lock' ]]
    then
        echo "storage/lock still existing after storage quit" >&2
        exit 1
    fi
    rm -rf 'storage' 'early-watch.actual.log' 'late-watch.actual.log' 'past-watch.actual.log' 'watch.actual.log'
}

rm -rf 'storage' 'early-watch.actual.log' 'late-watch.actual.log' 'past-watch.actual.log' 'watch.actual.log'
mkdir 'storage'

evr-glacier-storage &
spid=$!
trap stop EXIT

wait_for_glacier_storage

# tests that watch will report blobs modified while the watch was
# live.
( evr watch > early-watch.actual.log ) &
ewpid=$!

sleep 1

ref=`echo "hello world!" | evr put`
echo "evr reported ref ${ref}"
body=`evr get ${ref}`
if [[ "hello world!" != "${body}" ]]
then
    echo "Unexpected get response: ${body}" >&2
    exit 1
fi
echo 'another one' | evr put --flags 1

( evr watch > late-watch.actual.log ) &
lwpid=$!

# tests that watch will report blobs modified before the watch was
# initiated.
( evr watch --last-modified-after 0 > past-watch.actual.log ) &
pwpid=$!

now=`date +%s`
future=`expr 60000 + ${now} '*' 1000`
( evr watch --last-modified-after "${future}" > future-watch.actual.log ) &
fwpid=$!

( evr watch --flags-filter 1 --last-modified-after 0 > claims-watch.actual.log ) &
cwpid=$!

sleep 1

kill "${ewpid}"
kill "${lwpid}"
kill "${pwpid}"
kill "${fwpid}"
kill "${cwpid}"

if [[ -s late-watch.actual.log ]]
then
    echo "Expected late-watch.actual.log to be empty but was:" >&2
    cat late-watch.actual.log >&2
    exit 1
fi

for prefix in early past
do
    awk '{FS = " "} {print $1}' < "${prefix}-watch.actual.log" > watch.actual.log
    if ! diff watch.expected.log watch.actual.log
    then
        echo "Expected watch.expected.log to equal ${prefix}-watch.actual.log" >&2
        exit 1
    fi
    awk '{FS = " "} {print $3}' < "${prefix}-watch.actual.log" > watch-flags.actual.log
    if ! diff "${prefix}-watch-flags.expected.log" watch-flags.actual.log
    then
        echo "Expected ${prefix}-watch-flags.expected.log to equal $f" >&2
        exit 1
    fi
done

awk '{FS = " "} {print $1}' < "claims-watch.actual.log" > watch.actual.log
if ! diff 'claims-watch.expected.log' 'watch.actual.log'
then
    echo "Expected claims-watch.expected.log to equal watch.actual.log" >&2
    exit 1
fi

if [[ -s future-watch.actual.log ]]
then
    echo "Expected future-watch.actual.log to be empty but was:" >&2
    cat future-watch.actual.log >&2
    exit 1
fi
