#!/bin/bash
set -e
. ../config

stop(){
    kill -s sigint "${spid}"
    wait "${spid}" || true
    if [[ -e 'storage/lock' ]]
    then
        echo "storage/lock still existing after storage quit" >&2
        exit 1
    fi
    rm -rf 'storage' 'files'
}

rm -rf 'storage' 'files'
mkdir 'storage' 'files'

echo 'hello world!' > './files/hello.txt'

evr-glacier-storage &
spid=$!
trap stop EXIT

test_file_put_pop(){
    local base_name="$1"
    ref=`evr-glacier-cli post-file "files/${base_name}.txt"`
    echo "evr-glacier-cli reported ref ${ref}"
    claim=`evr-glacier-cli get ${ref}`
    echo "claim: ${claim}"
    if [[ -z "${claim}" ]]
    then
        echo "Claim was empty" >&2
        exit 1
    fi
    echo "evr-glacier-cli get-file ${ref}"
    evr-glacier-cli get-file "${ref}" > "files/${base_name}.get.txt"
    echo "Comparing ${base_name} posted with get file"
    diff "files/${base_name}.txt" "files/${base_name}.get.txt"
    echo "${base_name} file looks good"
}

wait_for_glacier_storage

test_file_put_pop "hello"

# produce a 32mb file
dd if=/dev/random bs=4096 count=8192 of=files/big.txt
test_file_put_pop "big"

# it should use custom title if -t arg present
ref=`evr-glacier-cli post-file -t 'my file name' 'files/hello.txt'`
claim=`evr-glacier-cli get ${ref}`
if [[ "${claim}" != *"my file name"* ]]
then
    echo "Claim should have used title 'my file name': ${claim}" >&2
    exit 1
fi
