#!/bin/bash
set -e
. ../config

stop(){
    kill -s sigint "${spid}"
    wait "${spid}" || true
    if [[ -e 'storage/lock' ]]
    then
        echo "storage/lock still existing after storage quit" >&2
        exit 1
    fi
    rm -rf 'storage' 'files'
}

rm -rf 'storage' 'files'
mkdir 'storage' 'files'

echo 'hello world!' > './files/hello.txt'

evr-glacier-storage &
spid=$!
trap stop EXIT

wait_for_glacier_storage
ref=`evr-glacier-cli post-file './files/hello.txt'`
echo "evr-glacier-cli reported ref ${ref}"
claim=`evr-glacier-cli get ${ref}`
echo "claim: ${claim}"
if [[ -z "${claim}" ]]
then
    echo "Claim was empty" >&2
    exit 1
fi
