# everarch - the hopefully ever lasting archive
# Copyright (C) 2021-2023  Markus Peröbner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FROM docker.io/library/alpine:3.18 AS builder
LABEL org.opencontainers.image.authors="markus.peroebner@gmail.com"
LABEL org.opencontainers.image.licenses="AGPL-3.0"
LABEL org.opencontainers.image.source="https://github.com/marook/everarch"
RUN apk update && apk add gcc musl-dev make autoconf automake pkgconfig libtool argp-standalone libxml2-dev libxslt-dev openssl-dev gpgme-dev libgcrypt-dev sqlite-dev
WORKDIR /root/everarch
COPY . /root/everarch
RUN autoreconf --install && ./configure && make clean && cd src && make -j 4 evr-glacier-storage

FROM docker.io/library/alpine:3.18 AS image
LABEL org.opencontainers.image.authors="markus.peroebner@gmail.com"
LABEL org.opencontainers.image.licenses="AGPL-3.0"
LABEL org.opencontainers.image.source="https://github.com/marook/everarch"

EXPOSE 2361

# the volume /pub exposes the TLS certificate and auth-token necessary
# to access this evr-glacier-storage instance. this volume should be
# shared with containers which want to access this evr-glacier-storage
# instance.
VOLUME /pub

# the volume /data stores the state of the evr-glacier-storage instance.
# this volume should not be shared with other containers.
VOLUME /data

RUN apk update && apk add sqlite-libs libgcrypt openssl

COPY README AUTHORS COPYING /opt/evr/
COPY etc/podman/entrypoints/prepare_auth_token etc/podman/entrypoints/prepare_tls_cert /opt/evr/entrypoint/
COPY etc/podman/evr-glacier-storage/entrypoint.sh /
COPY etc/podman/entrypoints/cert.conf /opt/evr/
COPY --from=builder /root/everarch/src/evr-glacier-storage /opt/evr/

CMD ["/entrypoint.sh"]
