#!/bin/bash
set -e
set -o pipefail
. ../config

allocate_ports
write_evr_conf
trap stop_everarch_servers EXIT

start_glacier_storage
wait_for_glacier_storage

echo "Uploading basic attr-spec…"
basic_xslt_ref=`evr put < basic.xslt`
evr -f 3 sign-put <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<claim-set
    xmlns="https://evr.ma300k.de/claims/"
    xmlns:dc="http://purl.org/dc/terms/"
    dc:created="2022-03-01T00:00:00.000000Z"
    >
  <attr-spec>
    <attr-def k="tag" type="str"/>
    <attr-def k="title" type="str"/>
    <transformation type="xslt" blob="${basic_xslt_ref}"/>
  </attr-spec>
</claim-set>
EOF

fs_xslt_ref=`evr put < fs.xslt`

start_attr_index
wait_for_attr_index

mount_evr_fs "${fs_xslt_ref}"

sleep 0.5

kill -s sigint "${attr_index_pid}"
wait "${attr_index_pid}" || true
attr_index_pid=

echo "Stopping…"
