# everarch - the hopefully ever lasting archive
# Copyright (C) 2021-2023  Markus Peröbner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FROM docker.io/library/alpine:3.18 AS builder
LABEL org.opencontainers.image.authors="markus.peroebner@gmail.com"
LABEL org.opencontainers.image.licenses="AGPL-3.0"
LABEL org.opencontainers.image.source="https://github.com/marook/everarch"

RUN apk update && apk add gcc musl-dev make autoconf automake pkgconfig libtool texinfo argp-standalone libxml2-dev libxslt-dev openssl-dev gpgme-dev libgcrypt-dev sqlite-dev fuse3-dev
WORKDIR /root/everarch
COPY . /root/everarch
RUN autoreconf --install && ./configure && make clean && cd src && make -j 4 evr-parallel evr-glacier-fs finally

FROM docker.io/library/nginx:1.25.3-alpine3.18 AS image
LABEL org.opencontainers.image.authors="markus.peroebner@gmail.com"
LABEL org.opencontainers.image.licenses="AGPL-3.0"
LABEL org.opencontainers.image.source="https://github.com/marook/everarch"

# http port
EXPOSE 80

# the volume /pub exposes the public GPG keys used and auth-token
# necessary to access the other evr services.
VOLUME /pub

# the volume /data stores the state of the evr-web instance. this
# volume should not be shared with other containers.
VOLUME /data

RUN apk update && apk add libxml2 libxslt gpgme fuse3 util-linux

COPY README AUTHORS COPYING /opt/evr/
COPY etc/podman/evr-web/envsubst-var-fix.sh /docker-entrypoint.d/18-envsubst-var-fix.sh
COPY etc/podman/evr-web/nginx.conf /etc/nginx/templates/default.conf.template
COPY etc/podman/entrypoints/wait_for_file /opt/evr/entrypoint/
COPY etc/podman/evr-web/entrypoint.sh /opt/evr/entrypoint.sh
COPY evr-web/dist/. /opt/evr/evr-web/
COPY --from=builder /root/everarch/src/evr-parallel /root/everarch/src/evr-glacier-fs /root/everarch/src/finally /opt/evr/

ENTRYPOINT ["/opt/evr/entrypoint.sh"]
